```mermaid
graph LR
    subgraph T2 [Timeline]
        direction TB
        B1[Node 1] --> B2[Node 2]
        B2 --> B3[Node 3A]
        B3 --> B4[Node 4A]
        B2 --> B5[Node 3B]
        B5 --> B6[Node 4B]
    end
```
